id: IB9F5B4B5
legacy_id: P004152
ocr_import_info:
  bdrc_scan_id: W22349
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T06:36:56'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T21:24:52.980494+00:00'
last_modified: 2022-09-02 05:25:01.112731
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22349
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22349
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསྡུས་གྲྭའི་རྣམ་གཞག་ཆ་ཚང་བ་རིག་གནས་ལེགས་བཤད་བང་མཛོད།
  author: འཕྲིན་ལས་ལྷུན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.5246752061236112
  ocr_word_median_confidence_index: 0.5
quality: null
bases:
  I1KG1383:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1383
      total_pages: 198
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG1383.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5246752061236112
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
