id: P004152
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:56:45.630280
source_metadata:
  id: bdr:W22349
  title: བསྡུས་གྲྭའི་རྣམ་གཞག་ཆ་ཚང་བ་རིག་གནས་ལེགས་བཤད་བང་མཛོད
  author: ''
  volumes:
    0e86dfa4861547e5892dd1e977cc8e2d:
      image_group_id: I1KG1383
      title: ''
      volume_number: 1
      total_pages: 198
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
